### PR TITLE
Issue 88: Fixed Alt Text for the Image tags for icons

### LINKED ISSUE #88: [UAT] Testing across browsers - Safari, Edge, Edge (Windows) & Chrome
1. Header issue - sticky for Safari. Fixed
2.  The links under "Subscribe for Podcasts" are not opening in the New Tab.

### PR DESCRIPTION
**Pull request by shrotia**
Fix #88 

Test URLs:
- Before: https://main--infosys--aemsites.hlx.live/iki
- After: https://issue-88-v2--infosys--aemsites.hlx.live/iki

### CODE REVIEW

File: blocks/subscription/subscription.js [hunk 1]
```diff
@@ -129,6 +129,10 @@ export default async function decorate(block) {
   [...block.children].forEach((row) => {
     const titleLinkDiv = row.children[0];
     const popupDiv = row.children[1];
+    const links = row.querySelectorAll('a');
+    links.forEach((link) => {
+      link.setAttribute('target', '_blank');
+    });
```
Comment (anuj-adobe) [inline blocks/subscription/subscription.js:135]: these changes are present in this PR as well? - https://github.com/aemsites/infosys/pull/97/files

**Review by anuj-adobe — APPROVED** [review]
